### ISSUE TITLE
思源使用随机端口的解决方案 | The solutions of SiYuan using a random port

### ISSUE THREAD

**Issue by wangcb80** [Zuoqiu-Yingyi/widget-url-scheme#1]
转换后的链接已经不在可用，端口存在问题

**Comment by Zuoqiu-Yingyi** [comment]
目前思源为了解决 6806 端口占用问题, 使用了随机端口, 不过有两种固定的解决方案

#### 带参数启动思源

假设想要使用指定的端口 `12345` 启用思源

创建一个思源快捷方式, 快捷方式的目标添加 `--port=12345` 参数

例如 `C:\思源安装目录\SiYuan.exe --port=12345`

#### 默认使用 6806 端口

虽然思源使用的随机端口, 但是第一个打开的工作空间可以同时使用 6806 端口访问, 因此可以在浏览器中访问 `http://localhost:6806/widgets/url-scheme/` 以使用该挂件, 原来的链接也不会失效

**Comment by Zuoqiu-Yingyi** [comment]
`v0.2.0+` 版本添加了一个复选框, 勾选后可以强制使用 `6806` 端口\~
